# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := GlUtils gtest test1_example Sfml-Glm-OpenGL-Glew-Example Triangle_Example

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

GlUtils: 
	@echo "==== Building GlUtils ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f GlUtils.make

gtest: 
	@echo "==== Building gtest ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f gtest.make

test1_example: gtest
	@echo "==== Building test1_example ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f test1_example.make

Sfml-Glm-OpenGL-Glew-Example: GlUtils
	@echo "==== Building Sfml-Glm-OpenGL-Glew-Example ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Sfml-Glm-OpenGL-Glew-Example.make

Triangle_Example: GlUtils
	@echo "==== Building Triangle_Example ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Triangle_Example.make

clean:
	@${MAKE} --no-print-directory -C build -f GlUtils.make clean
	@${MAKE} --no-print-directory -C build -f gtest.make clean
	@${MAKE} --no-print-directory -C build -f test1_example.make clean
	@${MAKE} --no-print-directory -C build -f Sfml-Glm-OpenGL-Glew-Example.make clean
	@${MAKE} --no-print-directory -C build -f Triangle_Example.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GlUtils"
	@echo "   gtest"
	@echo "   test1_example"
	@echo "   Sfml-Glm-OpenGL-Glew-Example"
	@echo "   Triangle_Example"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
